# Generated by Django 4.2.3 on 2023-07-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galareya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('gibrid', models.CharField(max_length=255)),
                ('max_speed', models.CharField(max_length=255)),
                ('motor', models.CharField(max_length=255)),
                ('passangers', models.CharField(max_length=255)),
                ('battery_capacity', models.CharField(max_length=255)),
                ('max_cruising_range', models.CharField(max_length=255)),
            ],
        ),
    ]
