# Generated by Django 4.2.3 on 2023-07-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandDmotors', '0002_alter_galareya_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='galareya',
            name='slug',
            field=models.SlugField(default=True),
            preserve_default=False,
        ),
    ]
