# Generated by Django 4.2.3 on 2023-07-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CandDmotors', '0005_galareya_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galareya',
            name='name',
        ),
    ]
