# Generated by Django 4.2.3 on 2023-07-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandDmotors', '0007_galareya_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='galareya',
            name='image',
            field=models.ImageField(default=True, upload_to='Cars'),
            preserve_default=False,
        ),
    ]
