# Generated by Django 4.2.3 on 2023-07-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandDmotors', '0008_galareya_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galareya',
            name='battery_capacity',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galareya',
            name='max_cruising_range',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galareya',
            name='max_speed',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galareya',
            name='motor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galareya',
            name='passangers',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
