# Generated by Django 4.2.3 on 2023-07-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandDmotors', '0011_alter_galareya_battery_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galareya',
            name='motor',
            field=models.FloatField(null=True),
        ),
    ]
